version: '3'
services:
  webcrawler:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mongodb
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_HOST=mongodb://mongodb:27017
    ports:
      - 5000:5000
    networks:
      - local

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - local

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - local


networks:
  local:
